CREATE TABLE "__drizzle_migrations" (
			id SERIAL PRIMARY KEY,
			hash text NOT NULL,
			created_at numeric
		);
INSERT INTO "__drizzle_migrations" VALUES(NULL,'8ba86bbfcb7c9254b09f73b1b6b272db671c38de8a93d16d8efb4a50dc102e07',1772146034595);
INSERT INTO "__drizzle_migrations" VALUES(NULL,'dfc94831fc089ba9695cc9497524cf10d01e0181a4549cc969e53d73a9580410',1772326034999);
CREATE TABLE _hub_migrations (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  name       TEXT UNIQUE,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "articles" (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text NOT NULL,
	`slug` text NOT NULL,
	`content` text NOT NULL,
	`excerpt` text,
	`featured_image` text,
	`category` text,
	`tags` text,
	`author` text DEFAULT 'Jean-Hugues GODONOU' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`publish_date` text NOT NULL,
	`meta_title` text,
	`meta_description` text,
	`created_at` text DEFAULT '2026-03-01T14:09:14.585Z',
	`updated_at` text DEFAULT '2026-03-01T14:09:14.587Z'
);
INSERT INTO "articles" VALUES(6,'Les bugs dans le code','les-bugs-dans-le-code','<p>Je vous assure qu’il y a des bugs qui se résolvent tout seuls. Je m’explique<br>Tu connais ce moment où :<br> • tu fixes ton écran depuis 3 heures,<br> • tu relis la même ligne de code 47 fois,<br> • tu insultes ton code, tu lui balances des insultes à la figure du genre :<br> « Toi, c’est quoi ton put*an de problème ?<br> Pourquoi tu ne fonctionnes pas ?<br> N*que ta race, n*que ta mère, le commissaire et son salaire de misère »<br> (dédicace spéciale à La Fouine )<br> • et RIEN. Le bug refuse de coopérer 😤<br>Alors tu fais quoi ?<br> -Tu lâches tout.<br> -Tu vas manger.<br> -Tu vas dormir.<br> -Tu penses à autre chose.<br>Et là<br>-&nbsp;Sous la douche<br> -Dans le taxi<br> -Juste avant de t’endormir<br> -Ou en faisant tout autre chose<br> BOOM.<br> La solution apparaît comme par magie.<br>Tu retournes au code :<br> •2 minutes<br> • 1 console.log<br> • 1 « Ah mais OUI donc c’était TOI qui mettais mes nerfs à rude épreuve 🤦‍♂️ »<br> • Bug corrigé.<br>Tous les bugs ne se résolvent pas avec plus de code.<br><br> Certains se résolvent avec moins d’écran et plus de cerveau au repos.<br> Se déconnecter, c’est parfois la meilleure technique de debug.<br><br>Les devs comprendront.<br> Les autres croiront qu’on exagère 😅</p>','Je vous assure qu’il y a des bugs qui se résolvent tout seuls. Je m’expliqueTu connais ce moment où : • tu fixes ton écran depuis 3 heures, • tu relis la même l...','/images/1772490833156-les-bugs-dans-le-code.jpg',NULL,'["dev web"]','Jean-Hugues GODONOU','published','2026-03-02T22:33:53.068Z','Les bugs dans le code','Je vous assure qu’il y a des bugs qui se résolvent tout seuls. Je m’expliqueTu connais ce moment où : • tu fixes ton écran depuis 3 heures, • tu relis la même l...','2026-03-02T22:11:18.470Z','2026-03-02T22:11:18.470Z');
INSERT INTO "articles" VALUES(7,'warnings dans l''éditeur','warnings-dans-lediteur','<p>Est-ce que les warnings dans l''éditeur ralentissent la vitesse d’exécution du code ?<br> Non mais presque 😄<br>Enfin, pas comme tu le penses.<br><br>Les warnings (jaunes, orange, ESLint, TypeScript, etc.) ne ralentissent PAS ton code à l’exécution.<br>Ton navigateur ou ton serveur s’en fiche complètement.<br><br>Mais Ils peuvent ralentir ton projet d’une autre manière.<br><br>Pourquoi les warnings sont importants ?<br>Ils signalent du code inutile (variables jamais utilisées, imports morts)<br>Ils révèlent des risques de bugs futurs<br>Ils indiquent des mauvaises pratiques qui rendent le code difficile à maintenir<br><br> Résultat :<br>Même si ton app tourne vite aujourd’hui, toi tu ralentis demain :<br>debugging plus long<br>refacto plus compliquée<br>onboarding difficile sur le projet<br><br> Le vrai danger<br>Ce n’est pas la performance machine<br>C’est la performance du développeur.<br>Un code plein de warnings =<br>- dette technique<br>- perte de clarté<br>- perte de temps<br><br>Le bon réflexe serait de corriger les warnings dès que possible.<br>Ne pas les ignorer parce que ça marche.<br>Voir les warnings comme des conseils, pas des ennemis<br></p>','Est-ce que les warnings dans l''éditeur ralentissent la vitesse d’exécution du code ? Non mais presque 😄Enfin, pas comme tu le penses.Les warnings (jaunes, oran...','/images/1772491746426-warnings-dans-l''editeur.png',NULL,'["warnings","Bug"]','Jean-Hugues GODONOU','published','2026-03-02T22:49:06.403Z','warnings dans l''éditeur ','Est-ce que les warnings dans l''éditeur ralentissent la vitesse d’exécution du code ? Non mais presque 😄Enfin, pas comme tu le penses.Les warnings (jaunes, oran...','2026-03-02T22:44:21.425Z','2026-03-02T22:44:21.425Z');
INSERT INTO "articles" VALUES(8,'Organisation des dossiers dans un projet Front-end','organisation-des-dossiers-dans-un-projet-front-end','<p>Comment j’organise mes dossiers dans un projet Front-end.<br>On prend l"exemple de Nuxt.js <br><br>Dans un projet professionnel, la structure compte presque autant que le code.<br><br> Une bonne organisation = productivité + crédibilité.<br>Voici ma logique :<br>- pages: toutes les pages du site<br>- components: composants réutilisables<br>- composables: fonctions logiques partagées<br>- layouts: modèles de page (dashboard, landing…)<br>- assets: images, styles, icônes<br> -plugins: librairies et outils externes<br> - stores: état global si besoin (Pinia)<br><br> Astuce pro<br> Toujours garder la logique facile à comprendre pour un autre dev.<br><br> Si quelqu’un rejoint ton projet, il doit retrouver l’information qu''il cherche rapidement</p>','Comment j’organise mes dossiers dans un projet Front-end.On prend l"exemple de Nuxt.js Dans un projet professionnel, la structure compte presque autant que le c...','/images/1772491957763-organisation-des-dossiers-dans-un-projet-front-end.jpg',NULL,'["warnings","Bug"]','Jean-Hugues GODONOU','published','2026-03-02T22:52:37.745Z','Organisation des dossiers dans un projet Front-end','Comment j’organise mes dossiers dans un projet Front-end.On prend l"exemple de Nuxt.js Dans un projet professionnel, la structure compte presque autant que le c...','2026-03-02T22:44:21.425Z','2026-03-02T22:44:21.425Z');
INSERT INTO "articles" VALUES(10,'Peut-on se passer des framework ?','peut-on-se-passer-des-framework','<p>Peut-on se passer des framework ?<br><br><br><br><br>Non.<br><br>Dans le domaine du dev web,les langages tels que le HTML,le CSS et le JS sont suffisant pour créér des sites web.On peut donc croire que les framework ne sont plus utile alors que non.<br><br><br><br>Les frameworks apportent bien plus que ce que ces langages de base peuvent offrir nous pouvons citer par exemple :<br><br>Gain de temps : Les frameworks comme React ou Vue.js permettent de développer plus rapidement en réutilisant des composants.<br><br><br>Performance : Ces outils optimisent le rendu et la mise à jour de l''interface, améliorant la réactivité et l’expérience utilisateur.<br><br><br><br>Scalabilité : Ils facilitent la gestion de projets complexes et de grande envergure grâce à une structure claire et modulable.<br><br><br><br>Notons que avant de se lancer sur un framework il fait avoir un bonne maîtrise des langages de base.<br></p>','Peut-on se passer des framework ?Non.Dans le domaine du dev web,les langages tels que le HTML,le CSS et le JS sont suffisant pour créér des sites web.On peut do...','/images/1772492304586-peut-on-se-passer-des-framework.png',NULL,'["back-end","front-end"]','Jean-Hugues GODONOU','published','2026-03-02T22:58:24.567Z','Peut-on se passer des framework ?','Peut-on se passer des framework ?Non.Dans le domaine du dev web,les langages tels que le HTML,le CSS et le JS sont suffisant pour créér des sites web.On peut do...','2026-03-02T22:44:21.425Z','2026-03-02T22:44:21.425Z');
INSERT INTO "articles" VALUES(11,'lE JS peut-il faire du backend?','le-js-peut-il-faire-du-backend','<p>Le JS ne devrait pas faire du back-end.<br>Le JS peut faire du back-end.<br><br>Très honnêtement ? Ce débat revient tout le temps <br><br>Et il mérite une réponse nuancée, pas idéologique selon moi.<br><br>Pourquoi certains devs back-end disent que JS n’est pas fait pour le back-end<br><br>JavaScript est historiquement un langage orienté front.<br><br>L’écosystème Node a longtemps été vu comme jeune ou instable.<br><br>Comparé à Java, C#, Go etc... ça donne parfois moins de cadre par défaut<br><br><br>Pourquoi JS est pourtant utilisé en back-end aujourd’hui?<br><br>Node.js est ultra performant pour les apps.<br><br>Le même langage front + back, c’est un vrai gain de productivité.<br><br>L’écosystème est énorme (Express, NestJS, etc.)<br><br><br>La vraie question n’est pas JS est-il bon ou mauvais ?<br><br>Mais plutôt :<br><br>Pour quel type de projet ?<br><br>Avec quelles pratiques ?<br><br>Avec quelle équipe ?<br><br>Un back-end en JS mal structuré sera mauvais.<br><br>Un back-end en Java ou PHP mal structuré le sera tout autant.<br><br>Avec de bonnes conventions, des tests, une bonne architecture (et éventuellement TypeScript), JS fait très bien le job.</p>','Le JS ne devrait pas faire du back-end.Le JS peut faire du back-end.Très honnêtement ? Ce débat revient tout le temps Et il mérite une réponse nuancée, pas idéo...','/images/1772492697181-le-js-peut-il-faire-du-backend.png',NULL,'[]','Jean-Hugues GODONOU','published','2026-03-02T23:04:57.171Z','lE JS peut-il faire du backend?','Le JS ne devrait pas faire du back-end.Le JS peut faire du back-end.Très honnêtement ? Ce débat revient tout le temps Et il mérite une réponse nuancée, pas idéo...','2026-03-02T22:44:21.425Z','2026-03-02T22:44:21.425Z');
CREATE UNIQUE INDEX `articles_slug_unique` ON `articles` (`slug`);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('articles',11);
